// Copyright 2024 eebor. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "querygen"; DO NOT EDIT.

package builders

import (
	query "github.com/eebor/sweetquery/query"
	srcpkg "github.com/eebor/sweetquery/testpackage"
)

func BuildReq(req *srcpkg.Req) []byte {
	q := query.NewQuery()
	q.WriteInt("id", req.Id)
	q.WriteInt("id", req.Balance)
	if req.IsPremium != nil {
		q.WriteBool("is_premium", *req.IsPremium)
	}
	return q.Bytes()
}
